### ISSUE TITLE
Feat: 앨범 속 이미지 관리

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#16]
## Progress
앨범 속에 있는 이미지들을 관리하는 전반적인 작업 진행

## Todo
- [x] 외부 파일 드래그앤드롭 시 해당 이미지 정보 가져오기
- [x] 이미지 위치 이동 및 값 관리
- [x] 이미지 사이즈 리사이징

## ETC
- 이미지 지우기는 이후에
