### ISSUE TITLE
Feat: 앨범 바디 데이터 관리(ex- 이미지..)

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#18]
## Progress
작업 진행 사항

## Todo
- [ ] 이미지 비율 생각하기
- [ ] 캔버스 범위 내에서만 이동 및 사이즈 조절 가능
- [ ] 이미지 우선순위(z-index) 설정

## ETC
- [ ] 그룹화
- [ ] 이미지 범위 밖으로 보내면 삭제되게 하기
