### ISSUE TITLE
Feat: 앨범 생성 및 유저 정보 받아오기

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#31]
## Progress
제목을 입력하는 단계를 거쳐 앨범을 생성하고 생성한 앨범과 이름, 기타 정보를 포함한 유저 정보를 받아 메인페이지에 렌더한다.

## Todo
- [x] 제목 입력 후 생성하면 소켓 통신 열림
- [x] 앨범은 특수한 id로 구분되야함
- [x] 유저 정보 메인페이지에 렌더

## ETC
~~유저 초대 어떤식으로 할지 방식 생각 잘 해보자~~ -> 유저 초대는 일단 친구 신청 후 해야해서 다음에(추가 UI 작업도 해야함)
