### ISSUE TITLE
Feat: 앨범 섹션 모달 UI 생성

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#36]
## Progress
앨범에 있는 정보, 구성원 모달 UI 구성하기

## Todo
- [x] 정보 모달 UI
- [x] 구성원 모달 UI

## ETC
~- [ ] 입장 시 welcome message 보내기(앨범 데이터 받기 위해서)~
- [x] 입장 시 앨범 정보 받기(제목, ~구성원, 정보~) -> api요청
