### ISSUE TITLE
Feat: 친구 추가 구현하기

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#38]
## Progress
친구 추가를 위한 UI 및 구현 완료하기

## Todo
- [x] 초대 popUp 생성
- [x] 이름 검색 시 api 요청
- [x] 초대 시 초대 대상에게 알림창 띄우기 및 알림아이콘에 표시
- [x] 수락 및 거절 api -> 수락 시 각 유저의 friends 리스트에 추가됐는지 확인하기

## ETC
Server Sent Event 활용해보기
