### ISSUE TITLE
Feat: 기타 수정사항 리팩토링

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#45]
## Progress
-

## Todo
- [x] 네이버 로그인 버튼 이미지 변경
- [x] /user/profile route handler 생성
- [x] 함수 및 구조 리팩토링

## ETC
-
