### ISSUE TITLE
Feat: 친구 추가 기능 추가 구현

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#60]
## Progress
친구 추가 기능에 부가적인 부분 추가하기

## Todo
- [x] mockdata로 되어있는 친구 리스트 실제 값으로 변경하기
- [x] 초대를 보냈거나 이미 친구라면 검색리스트에서 따로 처리해주기
- [x] 친구 삭제 기능
- ~~짱친 등록 기능~~

## ETC
짱친 등록 기능 -> 알림 수신 거부 (추후 개발예정)
