### ISSUE TITLE
Feat: 메인페이지 UI 추가 및 수정

### ISSUE THREAD

**Issue by rlarlduf20** [rlarlduf20/jogakbo-FE#78]
## Progress
작업 진행이 안된 UI 추가 및 수정

## Todo
- [x] 네비게이션 바 아이콘 변경
- [x] 네비게이션 바 아이콘 hover 시 텍스트 추가
- ~[ ] 이미지 테두리 만들기~
- [x] 메인페이지 앨범리스트 뷰 수정
- ~[ ] 정렬 기능 -> 정렬 클릭 시 UI~
- [x] 기타 색상, 배치, 크기 등등
